var http = require('http'),
    url = require('url'),
    fs = require('fs');
 var express = require('express')
  , app = module.exports = express();
 var router=express.Router();
//var fs = require('fs');
// string generated by canvas.toDataURL()
router.get('/', function(req, res, next){
var img = "52.38.205.169:3000/api/img/Right_9660009901_20170707_172902_1023927555.jpg";
// strip off the data: url prefix to get just the base64-encoded bytes
var fs = require("fs");
  fs.writeFile("arghhhh.jpg", new Buffer(img, "base64"), function(err) {});
});
module.exports=router;